public enum TokenType {
    
    CREATE, TABLE, DROP, ALTER, ADD, PRIMARYKEY, NOTNULL, UNIQUE, DEFAULT, DOUBLE, INTEGER, BOOLEAN, CHAR, VARCHAR,
    IDENTIFIER, NUMBER, STRING, COMMA, SEMICOLON, LPAREN, RPAREN, UNKNOWN, EOF

}
